# Generated by Django 4.2.7 on 2024-08-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
