# Generated by Django 4.1 on 2024-11-02 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competition_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('В процессе', 'В процессе'), ('Отказано', 'Отказано'), ('Не подтверждён', 'Не подтверждён')], default='Не подтверждён', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='category',
            field=models.CharField(choices=[('Учитель', 'Учитель'), ('Ученик', 'Ученик')], default='Ученик', max_length=25),
        ),
    ]
