# Generated by Django 4.2.7 on 2024-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0002_feedbackform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='category',
            field=models.CharField(default='Ученик', max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_seccion',
            field=models.CharField(max_length=25),
        ),
    ]
