# Generated by Django 4.1 on 2024-12-07 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0002_pupil_user_id_teacher_fathername_teacher_profeccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='fathername',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 15, 45, 30, 256958)),
        ),
    ]
