# Generated by Django 4.1 on 2024-11-02 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0002_competitionfiles_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
