# Generated by Django 4.1 on 2024-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0003_competition_competition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('token', models.TextField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
