# Generated by Django 4.1 on 2024-12-07 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0003_pupil_fathername_alter_token_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 15, 45, 38, 24159)),
        ),
    ]
