# Generated by Django 4.2.7 on 2024-09-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0003_alter_users_category_alter_users_date_seccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
