# Generated by Django 4.1 on 2024-12-05 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0005_schooluser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 22, 57, 11, 608494)),
        ),
    ]
